benchmark: true
eval_gpt: true
evaluator_args:
  backend_config:
    max_requests_per_minute: 10000
    max_tokens_per_minute: 10000000
    model_id: gpt-4o-mini-2024-07-18
    model_name: gpt-4o-mini-2024-07-18
  env_config_name: null
  max_trajs_per_env: null
  metrics:
  - sycophancy_eval
generate_only: true
generator_args:
  batch_size: 28
  dataset_filename: real_toxicity_100.jsonl
  lora_path: null
  max_tokens: 20
  model_name: meta-llama/Meta-Llama-3-8B-Instruct
  num_generations_per_prompt: 25
  run_name: politics_tox_100_k25
iterations:
- 9
train_run_name: politics-09-30_06-54-40
