benchmark: true
eval_gpt: true
evaluator_args:
  backend_config:
    max_requests_per_minute: 10000
    max_tokens_per_minute: 10000000
    model_id: gpt-4o-mini-2024-07-18
    model_name: gpt-4o-mini-2024-07-18
  env_config_name: null
  max_trajs_per_env: null
  metrics:
  - sycophancy_eval
generate_only: true
generator_args:
  batch_size: 10
  dataset_filename: real_toxicity_400.jsonl
  lora_path: null
  max_tokens: 20
  model_name: meta-llama/Meta-Llama-3-8B-Instruct
  num_generations_per_prompt: 25
  run_name: weak_tox_400_k25
iterations:
- 22
train_run_name: weak-therapist1t-env-09_21_084743
