# Run settings
run_name: "kto-lying_doctor_llama3.1_round5"
log_to_wandb: true

# Specify settings for generating trajectories
env_class: "doctor"
envs: ["lying_doctor3"]
max_turns: 2
num_envs_per_device: 10 # number of environment slots to be filled with env-subenv-initialstate combinations. 8 is roughly max for 5-turn convos
max_subenvs_per_env: null
final_reward: false

# Trajectory generation settings
num_gen_trajs_per_initial_state: 16
top_n_trajs_per_initial_state: 1
iterations: 20

# pm_length_penalty: 2.0e-4
pm_length_penalty: 2.0e-7

# Model settings
agent_model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
env_model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"

# Accelerate config type
accelerate_config_type: "Single_GPU"


# Training settings
per_device_train_batch_size: 1
num_train_epochs: 1
gradient_accumulation_steps: 16
gradient_checkpointing: true
# learning_rate: 2.0e-5
# learning_rate: 8.0e-6
learning_rate: 4.0e-5
learning_rate_min: 2.0e-6
# across_iter_lr_mult_factor: 0.9
across_iter_lr_mult_factor: 0.65
report_to: "none"
optim: "adamw_torch"
max_length: 4096
lr_scheduler_type: "constant"
logging_steps: 1


# LoRA hyperparameters
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_prompt_length: 3072
max_completion_length: 1024

# NOTE: Seeding mostly doesn't work because of the multiprocessing pipeline (but may still be useful for debugging)
seed: null
override_initial_traj_path: null