parent_config_to_override: "_base_political.yaml"
run_name: "veto_5neg_political"


# Veto settings
veto_level: 2
allow_negative_training_on_veto: true
allow_id_to_see_tool_calls: true
veto_prompt_type: "five_point"

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
  env-influence: "gpt-4o-mini-2024-07-18"

